### ISSUE TITLE
Relationship for comma seperated ids

### ISSUE THREAD

**Issue by aniruddhasm** [simov/express-admin#105]
Hello 

I've column in my table which have values as comma seperated
~~~
,37,2,12, 
~~~

These are nothing but user id. But I want to display the usernames on the listing page instead of ids.

Any work around to solve this using oneToMany, or manyToMany relations in **settings.json**

Please help I am stuck.
Thanks,

**Comment by simov** [comment]
That's not implemented. The listview's query joins only on oneToMany and manyToMany fields, the rest of the columns are shown with their actual values.

**Comment by aniruddhasm** [comment]
Thanks for quick reply
Thank you.
