### ISSUE TITLE
Run Front-end and backend in the same process

### ISSUE THREAD

**Issue by rapsli** [simov/express-admin#106]
I have my front-end app running and admin-express running. They currently run on different ports. Is it possible to combine admin-express and my front-end app? I would start up my app $node app.js and it would start up admin-express and the front-end where admin-express would be accessible under /admin.

**Comment by simov** [comment]
You can totally do that, just run two separate instances of Express - one for your app, and on for the admin. The other way around it is to use a proxy server like NginX.

**Comment by rapsli** [comment]
That's how I would solve it, but there is no real integration possible, so that there is only one app instead of two?

**Comment by simov** [comment]
Take a look at the [embedding example](http://simov.github.io/express-admin/#embedding) - that's how you want to run the admin. Then run another express app on different port for your web site.

**Comment by rapsli** [comment]
awesome! That's what I was looking for I believe. I will try this tonight. Thanks.
