### ISSUE TITLE
Add or edit an entry doesn't work

### ISSUE THREAD

**Issue by carlosfaria94** [simov/express-admin#108]
Hi,

I'm having a strange behavior. I'm using PostgresSQL and Node 4.4 and simply trying to add or edit an entry. And it's returned a successful message: "Success: The record have been saved." but nothing it's added or edited in database. 
With -l flag it's returned a insert that I copy and directly execute in database, and voila, I finally successful insert the entry with SQL returned by the log.

So, what may be happening?

Thanks!

**Comment by simov** [comment]
If the record isn't saved for some reason you should receive back some error message from the database.

**Comment by carlosfaria94** [comment]
But in the fact I’m not receiving back the error message. Maybe the user hasn't a full permission? But he is the owner of the database..

It’s a really weird behavior.

**Comment by simov** [comment]
You can try the [examples](https://github.com/simov/express-admin-examples) first. They should be working, so you can compare your configuration with the one found in the examples.

**Comment by carlosfaria94** [comment]
Ok.. I try the example, and I obtain the same behavior that I had.. 
For example, it's returned a successful message: "Success: The record have been saved." and log: `tbl insert into "public"."item" ("name","description","image") values ('Test','test','test') returning "id" ; `, but nothing its aded.

So, I go to database and execute above sql and works now: http://i.imgur.com/YbcP0V5.png

I'm using PostgreSQL 9.4

**Comment by simov** [comment]
What flags do you pass to the admin? Copy/paste the command that you are using here.

**Comment by carlosfaria94** [comment]
`admin -v -l config/pg/`

**Comment by simov** [comment]
Remove -v and try again

**Comment by carlosfaria94** [comment]
It's working! Why -v flag interferes?

Thanks!

**Comment by simov** [comment]
That's stated in the docs:

> The -v flag that you're passing to the Express Admin app means that you are running the admin in development mode. In this mode the authentication and the database record updates are disabled.

Though almost at the bottom :)

**Comment by carlosfaria94** [comment]
Ups. Sry, I haven't read the last sentence.
