### ISSUE TITLE
language override

### ISSUE THREAD

**Issue by erwanjegouzo** [simov/express-admin#120]
Right now, there are no ways to update the language across the views, but this would be very handy to provide further customization capabilities.
How about we ad a `languages` property in the config file, like following, which would override the existing values? 

```
mysql: {},
app: {},
languages: {
  en: {
    home: 'My Home Page'
  }
}
```
Would you be open to it? I can submit a PR.

**Comment by simov** [comment]
I haven't touched this project for a while now and that's the reason why I don't want to change anything in it. It's not perfect but it still works for what it was initially designed for. So I would suggest you to fork this repository instead, apply your changes there, and point your express-admin dependency in your package.json file to your own fork.

**Comment by erwanjegouzo** [comment]
alright, thanks for your answer @simov
