### ISSUE TITLE
cli does not prompt for host on initializing a directory

### ISSUE THREAD

**Issue by tkodev** [simov/express-admin#129]
When running `admin ./sample`, prompts do not ask you for a hostname. If you don't have a database running on your computer, the cli will then throw an error after the prompts.

**Comment by vmehera123** [comment]
@simov

**Comment by khasburrahman** [comment]
@htkoca so how did you connect to the database? I too can't connect to my local database even though I set the user & password correctly, perhaps I should set the hostname in `server` config.json to `http://localhost` but doesn't work

**Comment by simov** [comment]
Hi, in v2 of the admin there is no longer a CLI and instead you just have to setup your config.json file manually. All [connection options](https://github.com/simov/express-admin#database-connection) are supported for your database driver. Also have a look at the [changelog](https://github.com/simov/express-admin/blob/main/CHANGELOG.md#v200-20230214) for any potential breaking changes.
