### ISSUE TITLE
Are there lifecycle event hooks for different actions such as update, insert, delete?

### ISSUE THREAD

**Issue by jdgriffith** [simov/express-admin#131]
I have added model event hooks in my API and need certain hooks to be fired on the admin side too to keep my Elastic Search instance in sync. Is there a hook mechanism or strategy?

**Comment by simov** [comment]
- https://simov.github.io/express-admin/#events
- https://github.com/simov/express-admin-examples/blob/master/config/custom/events/events.js

**Comment by jdgriffith** [comment]
Awesome! This will work for my purposes. Thanks!
