### ISSUE TITLE
Delete as default action

### ISSUE THREAD

**Issue by lubomirfiala** [simov/express-admin#133]
Well, I'm trying to use express-admin for first time and I like it!
but: Why is delete button considered as default action in forms? (when I hit enter > it remove record) 
and why is delete action without confirmation?
Is there any settings for this?

**Comment by simov** [comment]
That would do it https://github.com/simov/express-admin/commit/b4f9f4e528dfe255dd10cfa024bcc05d5a003910

**Comment by lubomirfiala** [comment]
Thanks!

**Comment by simov** [comment]
Published version 1.3.2 with the fix :tada:
