### ISSUE TITLE
Empty one to Many

### ISSUE THREAD

**Issue by waleedshabbir1** [simov/express-admin#155]
Is there an option to leave select empty or add new values for one to many relationship ? 

For example A product which has many new pictures and I can add those pictures while adding the product ?

**Comment by simov** [comment]
No, that's not supported, but I guess you can use a Many to One instead.

**Comment by waleedshabbir1** [comment]
Thank you. That works 

but it is showing all the columns of other table. Is it possible to hide the ID columns of that table ?

**Comment by simov** [comment]
Yes, you have to set their visibility to false in the configuration.

**Comment by waleedshabbir1** [comment]
yes got it. 
Thank you
