### ISSUE TITLE
Add search  in list  view

### ISSUE THREAD

**Issue by ajax13** [simov/express-admin#17]
Hi,

  The searching in list view pages, is it  possible ?

**Comment by MichaelLeachim** [comment]
@ajax13 can you share your solution?

**Comment by simov** [comment]
@MichaelLeachim there is a `filter` key that you can add to each table's `listview` key. See example here: https://github.com/simov/express-admin-examples/blob/master/config/mysql/settings.json#L145-L156

List all columns there that you want to be able to filter by. Then they will appear in the filter pane - click on the small icon next to the title in listview screen.

**Comment by MichaelLeachim** [comment]
@simov  Thanks a lot.  What do you think of adding search alias to wiki http://simov.github.io/express-admin?

**Comment by simov** [comment]
You mean a section about that in the docs? I do agree that this features feels a bit non present there.

**Comment by MichaelLeachim** [comment]
On 20 January 2016 at 22:02, simo <notifications@github.com> wrote:

> You mean a section about that in the docs? I do agree that this features
> feels a bit non present there.
>
Yes, that would be great.
