### ISSUE TITLE
Building a Website with Express-Admin

### ISSUE THREAD

**Issue by romans127** [simov/express-admin#53]
This is more of a question than an issue. Is it possible to use this application to build a website. 

For instance I would like to setup my backend using Express-Admin. What would be the best way to create an express website that will look at my pages and content then render them to the browser. Essentially like a CMS. Is this possible or is this not what express-admin is for ? 

Thank you in advance. 

Ryan

**Comment by waleedshabbir1** [comment]
i managed to use express-admin at admin path by setting everything in my main server file index.js 

However I want to use it inside some route and I only want to initialize it inside that route. 
is this possible ?
