### ISSUE TITLE
Roles/Groups/Permissions

### ISSUE THREAD

**Issue by frnco** [simov/express-admin#57]
Are there any plans to create permissions?

i.e. Some users being able to access only parts of  the admin.

If there are, what are the considerations on this feature up to now?

**Comment by Chleba** [comment]
Any update ? IT has been removed from milestones so it's not going to happen ?

**Comment by simov** [comment]
Yes, that feature is no longer planned, but with v2 of the admin it is a bit easier to setup multiple routes and at least set one instance of the admin to show/hide certain tables and/or make others editable or readonly by having two separate `settings.json` files and also 2 different users for each admin instance.
