### ISSUE TITLE
Forgot password workflow

### ISSUE THREAD

**Issue by knownasilya** [simov/express-admin#70]
Would be very beneficial about now :neckbeard: haha. Something on the login page takes you to a new page that takes a username/email and sends an email with a change password token url, which will display a change password form.

**Comment by simov** [comment]
Hi, in v2 of the admin user passwords are now stored in plain text and it is advisable to load them from external more secure storage before feeding them into the admin middleware. So this will eliminate the need of having a reset password workflow, sort of. Basically you will have to contact an admin, not ideal, but that workflow isn't really planned right now.
