### ISSUE TITLE
How to check user access in custom view?

### ISSUE THREAD

**Issue by ghost** [simov/express-admin#83]
I have a get request like "site.com/admin/fs/download?filename=blahblah.pdf", where fs is my custom view. How can I check in my custom view if user have access to express admin? Because now everyone can execute this query without login.

**Comment by devpony** [comment]
Ok, i checked out the auth.js and
```
if (!req.session.user) next();
```
works for me

**Comment by simov** [comment]
Yes, and you can have multiple users registered to use the admin - check out this [comment](https://github.com/simov/express-admin/issues/29#issuecomment-30514629)

Also if you are POSTing data to the server don't forget to add a [CSRF](http://en.wikipedia.org/wiki/Cross-site_request_forgery) token in your web forms, just check out how this is done in the editview template.
