### ISSUE TITLE
host in the initial setup run

### ISSUE THREAD

**Issue by casperin** [simov/express-admin#93]
When running the initial setup you can't specify a `host` (it just assumes `localhost`). Although it is easy enough to create your own `config.js` (where `host` can be specified), it is quite unfortunate as `settings.json` won't be created for you.

For anyone with the same problem who reads this, I got around this by basically mapping `localhost` to whichever ip I needed in `/etc/hosts` while running the setup.

Also the setup does not work well if you have no password set for your db.

**Comment by flyingsky** [comment]
After you failed to setup, you can manually change the config.json, then you can start it.

**Comment by casperin** [comment]
We did solve it in the end, and as far as I know (I am not on that project any more) we're still using the module happily. 👍 
I'll close the issue so you can get on with your day. Thanks for your work!
