### ISSUE TITLE
Custom control for column

### ISSUE THREAD

**Issue by markusuntera** [simov/express-admin#98]
Hi
Is it possible or are you planning to add custom controls for column? For example to add map (OpenLayers or Leaflet etc) for choosing location (save lat/long)?

**Comment by simov** [comment]
You can inject some js/jquery code inside the editview, and initialize your map accordingly. The column type will be regular text box. You just need to hook the map with the text field.

Take a look at the examples repository. You can find a few examples there showing how to add custom code in the browser.

**Comment by markusuntera** [comment]
Thanx. Managed to do it.

**Comment by vojtechvrbka** [comment]
Hi, 

Can you explain how you did it ?
Or could you please tell me specific example, I can't find any that injects js inside the editview.

Thank you

**Comment by simov** [comment]
Hi @vojtechvrbka ,

Take a look at this example: https://github.com/simov/express-admin-examples/tree/master/config/custom/editors
